export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_SELECTED_MOVIE = 'SET_SELECTED__MOVIE';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CLEAR_SELECTED_MOVIE = 'CLEAR_SELECTED_MOVIE';